import type { CatalogProduct } from "@/lib/products/types";

/**
 * NEWFIND product catalog — seed source for Discovery Products.
 *
 * To add a product later:
 * 1. Confirm a checkable source URL (magazine, official SNS, brand, news, survey).
 * 2. Confirm a real purchase URL (brand official or authorized retailer).
 * 3. Never invent celebrity 愛用 / 着用.
 * 4. Never use example.com or placeholder URLs.
 * 5. Append a CatalogProduct here and add public/products/{id}.svg.
 *
 * Celebrity claims are included only when a named media/brand source exists.
 */
export const CATALOG_PRODUCTS: CatalogProduct[] = [
  {
    id: "takami-skin-peel",
    name: "タカミスキンピール",
    brand: "TAKAMI",
    collections: ["beauty", "celebrity", "trending", "japan_brands"],
    subcategory: "skincare",
    subcategoryLabel: "スキンケア",
    description:
      "角質層に着目したタカミの角質美容水。田中みな実さんが美容誌インタビューで愛用を公言しているスキンケアです。",
    imageUrl: "/products/takami-skin-peel.svg",
    accent: "#f4efe8",
    celebrityName: "田中みな実",
    celebrityRelation: "愛用",
    sourceUrl: "https://maquia.hpplus.jp/skincare/news/114325/",
    sourceTitle: "MAQUIA「田中みな実さんのスキンケア」インタビュー",
    sourceKind: "magazine",
    purchaseUrl: "https://www.takami-labo.com/products/skinpeel",
    purchaseLabel: "タカミ公式通販へ",
    seller: "タカミ化粧品 公式通販",
    priceText: "5,720円（税込）/ 30mL",
    popularityScore: 98,
    publishedAt: "2024-01-01",
    tags: ["スキンケア", "美容液", "田中みな実", "角質ケア"],
  },
  {
    id: "suqqu-the-primer",
    name: "ザ プライマー",
    brand: "SUQQU",
    collections: ["beauty", "celebrity", "trending", "japan_brands"],
    subcategory: "makeup",
    subcategoryLabel: "コスメ・下地",
    description:
      "光の奥行きを出すSUQQUの化粧下地。田中みな実さんがMAQUIA系インタビューで愛用アイテムとして挙げています。",
    imageUrl: "/products/suqqu-the-primer.svg",
    accent: "#f7f1ea",
    celebrityName: "田中みな実",
    celebrityRelation: "愛用",
    sourceUrl: "https://www.locari.jp/posts/3553302/",
    sourceTitle: "LOCARI / MAQUIA「田中みな実さんの愛用コスメ」",
    sourceKind: "magazine",
    purchaseUrl: "https://www.suqqu.com/ja/categories/baseMakeup/primer/p/4973167536582",
    purchaseLabel: "SUQQU公式へ",
    seller: "SUQQU 公式オンラインストア",
    priceText: "11,000円（税込）/ 30g",
    popularityScore: 96,
    publishedAt: "2024-08-18",
    tags: ["下地", "プライマー", "田中みな実", "ベースメイク"],
  },
  {
    id: "sekkisei-brightening-lotion",
    name: "薬用雪肌精 ブライトニング エッセンス ローション",
    brand: "雪肌精 / KOSE",
    collections: ["beauty", "celebrity", "japan_brands", "trending"],
    subcategory: "skincare",
    subcategoryLabel: "スキンケア",
    description:
      "コーセーの代表的な和漢化粧水。新垣結衣さんがグローバルミューズを務め、インタビューで実際に使ってみた感想を語っています。",
    imageUrl: "/products/sekkisei-brightening-lotion.svg",
    accent: "#e8f3f2",
    celebrityName: "新垣結衣",
    celebrityRelation: "紹介",
    sourceUrl: "https://www.oricon.co.jp/news/2372037/full/",
    sourceTitle: "ORICON NEWS 新垣結衣インタビュー（雪肌精グローバルミューズ）",
    sourceKind: "news",
    purchaseUrl: "https://maison.kose.co.jp/site/sekkisei/g/gMTSC/",
    purchaseLabel: "Maison KOSÉで見る",
    seller: "Maison KOSÉ / 雪肌精公式",
    priceText: "4,180円（税込）/ 200mL",
    popularityScore: 94,
    publishedAt: "2025-03-01",
    tags: ["化粧水", "雪肌精", "新垣結衣", "日本ブランド"],
  },
  {
    id: "frederic-malle-portrait",
    name: "ポートレイト オブ ア レディー",
    brand: "FREDERIC MALLE",
    collections: ["fragrance", "celebrity", "trending"],
    subcategory: "edp",
    subcategoryLabel: "オードパルファム",
    description:
      "ターキッシュローズを贅沢に使ったシグネチャーフレグランス。川口春奈さんがBAILAの取材で3年以上愛用していると話しています。",
    scentNotes: "ローズ / パチョリ / フランキンセンス",
    imageUrl: "/products/frederic-malle-portrait.svg",
    accent: "#1f1a17",
    celebrityName: "川口春奈",
    celebrityRelation: "愛用",
    sourceUrl: "https://baila.hpplus.jp/beauty/bodyfragrance/74170",
    sourceTitle: "BAILA「川口春奈さんの愛用香水」ポートレイト オブ ア レディー",
    sourceKind: "magazine",
    purchaseUrl: "https://latelierdesparfums.jp/products/portrait-of-a-lady-edp",
    purchaseLabel: "公式取扱店で見る",
    seller: "l'atelier des parfums（ブルーベル・ジャパン）",
    priceText: "10,890円（税込）〜 / 10mL",
    popularityScore: 97,
    publishedAt: "2025-01-01",
    tags: ["香水", "オードパルファム", "川口春奈", "ローズ"],
  },
  {
    id: "le-labo-santal-33",
    name: "SANTAL 33",
    brand: "LE LABO",
    collections: ["fragrance", "celebrity", "trending"],
    subcategory: "edp",
    subcategoryLabel: "オードパルファム",
    description:
      "サンダルウッドを軸にしたル ラボの代表香。川口春奈さんがBAILAで約10年愛用していると語っています。",
    scentNotes: "サンダルウッド / カルダモン / アイリス",
    imageUrl: "/products/le-labo-santal-33.svg",
    accent: "#f3efe6",
    celebrityName: "川口春奈",
    celebrityRelation: "愛用",
    sourceUrl: "https://baila.hpplus.jp/beauty/bodyfragrance/74171",
    sourceTitle: "BAILA「川口春奈さんの愛用香水」ル ラボ サンタル 33",
    sourceKind: "magazine",
    purchaseUrl: "https://www.lelabofragrances.jp/products/santal-33_144",
    purchaseLabel: "ル ラボ公式へ",
    seller: "ル ラボ 公式オンラインショップ",
    priceText: "31,350円（税込）〜",
    popularityScore: 95,
    publishedAt: "2025-01-01",
    tags: ["香水", "サンタル", "川口春奈", "コロン"],
  },
  {
    id: "andbe-sheer-lip",
    name: "&be シアーリップ",
    brand: "&be",
    collections: ["beauty", "celebrity", "japan_brands"],
    subcategory: "makeup",
    subcategoryLabel: "コスメ・リップ",
    description:
      "河北裕介プロデュースの&beから、ブランドミューズ・川口春奈さん監修カラーを含むシアーリップ。公式がコラボレーションとして発表しています。",
    imageUrl: "/products/andbe-sheer-lip.svg",
    accent: "#f8e9ea",
    celebrityName: "川口春奈",
    celebrityRelation: "プロデュース",
    sourceUrl: "https://andbe-official.com/shop/information/1693",
    sourceTitle: "&be公式「&be × 川口春奈コラボリップ」",
    sourceKind: "brand_official",
    purchaseUrl: "https://andbe-official.com/shop/products/AB005SL",
    purchaseLabel: "&be公式で見る",
    seller: "&be 公式オンラインストア",
    priceText: "2,200円（税込）",
    popularityScore: 90,
    publishedAt: "2024-10-01",
    tags: ["リップ", "コスメ", "川口春奈", "&be"],
  },
  {
    id: "herlipto-our-story",
    name: "Eau de Parfum OUR STORY",
    brand: "Her lip to BEAUTY",
    collections: ["fragrance", "celebrity", "japan_brands", "trending"],
    subcategory: "edp",
    subcategoryLabel: "オードパルファム",
    description:
      "小嶋陽菜さんがCCOを務めるHer lip to BEAUTY初のオードパルファム。本人プロデュースとして公式プレスで発表されています。",
    scentNotes: "シーンごとに選べる5種（ROSE BLANCHE ほか）",
    imageUrl: "/products/herlipto-our-story.svg",
    accent: "#f6eef2",
    celebrityName: "小嶋陽菜",
    celebrityRelation: "プロデュース",
    sourceUrl: "https://prtimes.jp/main/html/rd/p/000000118.000074953.html",
    sourceTitle: "PR TIMES「Her lip to BEAUTY オードパルファム OUR STORY」",
    sourceKind: "press",
    purchaseUrl: "https://herlipto.jp/pages/brand-beauty",
    purchaseLabel: "Her lip to公式へ",
    seller: "Her lip to 公式オンラインストア",
    priceText: "8,500円（税込）/ 30mL",
    popularityScore: 93,
    publishedAt: "2024-12-12",
    tags: ["香水", "オードパルファム", "小嶋陽菜", "日本ブランド"],
  },
  {
    id: "burberry-her-parfum",
    name: "BURBERRY HER PARFUM",
    brand: "BURBERRY",
    collections: ["fragrance", "celebrity"],
    subcategory: "perfume",
    subcategoryLabel: "香水",
    description:
      "バーバリー ハーの新香。本田翼さんが発売イベントで実際に纏い、香りの印象を公の取材で語っています（イベントでの紹介）。",
    scentNotes: "チェリー / グルマン / アンバー / バニラ",
    imageUrl: "/products/burberry-her-parfum.svg",
    accent: "#f3d6de",
    celebrityName: "本田翼",
    celebrityRelation: "紹介",
    sourceUrl: "https://www.nikkansports.com/entertainment/news/202603260000536.html",
    sourceTitle: "日刊スポーツ「本田翼、BURBERRY HER PARFUMイベント」",
    sourceKind: "news",
    purchaseUrl: "https://jp.burberry.com/her-parfum-50ml-p40852291",
    purchaseLabel: "Burberry公式へ",
    seller: "Burberry 公式サイト",
    priceText: "19,030円 / 50mL",
    popularityScore: 86,
    publishedAt: "2026-03-26",
    tags: ["香水", "本田翼", "バーバリー"],
  },
  {
    id: "andbe-uv-primer",
    name: "&be UVプライマーリッチモイスト",
    brand: "&be",
    collections: ["beauty", "celebrity", "japan_brands"],
    subcategory: "makeup",
    subcategoryLabel: "コスメ・下地",
    description:
      "ツヤ肌補正・日焼け止め・美容液の3in1下地。Snow Man 佐久間大介さんが&beアンバサダー就任時の公式発表・取材で使用・お気に入りとして紹介されています。",
    imageUrl: "/products/andbe-uv-primer.svg",
    accent: "#f4f0ea",
    celebrityName: "佐久間大介",
    celebrityRelation: "アンバサダー",
    sourceUrl: "https://maquia.hpplus.jp/blog/chika_maquia/118428/",
    sourceTitle: "MAQUIA「佐久間大介さんが&beアンバサダー就任」",
    sourceKind: "magazine",
    purchaseUrl: "https://andbe-official.com/shop/products/AB003UVPMRM",
    purchaseLabel: "&be公式で見る",
    seller: "&be 公式オンラインストア",
    priceText: "3,080円（税込）/ 36g",
    popularityScore: 91,
    publishedAt: "2026-04-24",
    tags: ["下地", "UV", "佐久間大介", "&be"],
  },
  {
    id: "andbe-color-shampoo-pink",
    name: "&be カラーシャンプー C.Pink",
    brand: "&be HAIR",
    collections: ["beauty", "celebrity", "japan_brands"],
    subcategory: "haircare",
    subcategoryLabel: "ヘアケア",
    description:
      "暖色系ヘアカラー向けのカラーシャンプー。佐久間大介さんが発表会で自宅染めに使ったこと、周囲へのおすすめを公に話しています。",
    imageUrl: "/products/andbe-color-shampoo-pink.svg",
    accent: "#f7e6ee",
    celebrityName: "佐久間大介",
    celebrityRelation: "愛用",
    sourceUrl: "https://www.oricon.co.jp/news/2411107/full/",
    sourceTitle: "ORICON NEWS 佐久間大介（&be カラーシャンプー C.Pink）",
    sourceKind: "news",
    purchaseUrl: "https://andbe-official.com/shop/products/AB009COS-CP",
    purchaseLabel: "&be公式で見る",
    seller: "&be 公式オンラインストア",
    priceText: "1,980円（税込）",
    popularityScore: 88,
    publishedAt: "2025-02-05",
    tags: ["ヘアケア", "カラーシャンプー", "佐久間大介"],
  },
  {
    id: "uniqlo-airism-cotton-t",
    name: "エアリズムコットンT",
    brand: "UNIQLO",
    collections: ["fashion", "teen", "japan_brands", "trending"],
    subcategory: "tshirt",
    subcategoryLabel: "Tシャツ",
    description:
      "表はコットン、肌面はエアリズムの定番Tシャツ。YOUTH TIME JAPAN projectの高校生調査で、男子の服購入店舗1位がユニクロと報告されています。この商品自体の個別ランキングではなく、支持店舗の公式定番です。",
    imageUrl: "/products/uniqlo-airism-cotton-t.svg",
    accent: "#eef3f7",
    celebrityName: null,
    celebrityRelation: null,
    sourceUrl: "https://prtimes.jp/main/html/rd/p/000000027.000118654.html",
    sourceTitle: "PR TIMES「高校生が服を購入するお店ランキング」（YTJP調査）",
    sourceKind: "survey",
    purchaseUrl: "https://www.uniqlo.com/jp/ja/products/E465755-000/01",
    purchaseLabel: "ユニクロ公式へ",
    seller: "ユニクロ公式オンラインストア",
    priceText: "公式ページで確認",
    popularityScore: 92,
    publishedAt: "2025-09-24",
    tags: ["Tシャツ", "高校生", "ユニクロ", "エアリズム"],
  },
  {
    id: "uniqlo-airism-cotton-men",
    name: "エアリズムコットンオーバーサイズTシャツ",
    brand: "UNIQLO",
    collections: ["fashion", "teen", "japan_brands"],
    subcategory: "tshirt",
    subcategoryLabel: "Tシャツ",
    description:
      "ユニクロが「最も売れているベーシックTシャツ」とする公式ライン。高校生男子の購入店舗としてユニクロが調査1位という出典とあわせて、公式商品ページから確認できます。",
    imageUrl: "/products/uniqlo-airism-cotton-men.svg",
    accent: "#e9eef3",
    celebrityName: null,
    celebrityRelation: null,
    sourceUrl: "https://www.uniqlo.com/jp/ja/contents/feature/masterpiece/product/airism-cotton-oversized-t-shirt/",
    sourceTitle: "UNIQLO公式 Masterpiece「エアリズムコットンオーバーサイズTシャツ」",
    sourceKind: "brand_official",
    purchaseUrl: "https://www.uniqlo.com/jp/ja/men/tops/t-shirts/airism-cotton",
    purchaseLabel: "ユニクロ公式へ",
    seller: "ユニクロ公式オンラインストア",
    priceText: "1,990円〜",
    popularityScore: 89,
    publishedAt: "2026-03-01",
    tags: ["Tシャツ", "高校生男子", "ユニクロ"],
  },
  {
    id: "gu-sweat-hoodie",
    name: "スウェットパーカ",
    brand: "GU",
    collections: ["fashion", "teen", "japan_brands", "trending"],
    subcategory: "hoodie",
    subcategoryLabel: "パーカー",
    description:
      "GU公式のユニセックス スウェットパーカ。高校生調査では女子の服購入店舗1位がGUと報告されています。店舗人気の出典と、公式で買える定番パーカを分けて掲載しています。",
    imageUrl: "/products/gu-sweat-hoodie.svg",
    accent: "#f3f1ec",
    celebrityName: null,
    celebrityRelation: null,
    sourceUrl: "https://prtimes.jp/main/html/rd/p/000000027.000118654.html",
    sourceTitle: "PR TIMES「高校生が服を購入するお店ランキング」（YTJP調査）",
    sourceKind: "survey",
    purchaseUrl: "https://www.gu-global.com/jp/ja/products/E358476-000/00",
    purchaseLabel: "GU公式へ",
    seller: "GU公式オンラインストア",
    priceText: "公式ページで確認",
    popularityScore: 91,
    publishedAt: "2025-09-24",
    tags: ["パーカー", "高校生女子", "GU", "スウェット"],
  },
  {
    id: "gu-skirts",
    name: "GU スカート",
    brand: "GU",
    collections: ["fashion", "teen", "japan_brands"],
    subcategory: "skirt",
    subcategoryLabel: "スカート",
    description:
      "GU公式のレディース スカートカテゴリ。放課後ファッションの定番として、高校生女子に支持される店舗（調査1位）の公式商品群です。個別SKUの人気順位ではなく、公式で確認できるカテゴリを案内します。",
    imageUrl: "/products/gu-skirts.svg",
    accent: "#f7f3ee",
    celebrityName: null,
    celebrityRelation: null,
    sourceUrl: "https://www.ytjp.jp/2023/09/08/koukouseiresearch-clothes-shop",
    sourceTitle: "YOUTH TIME JAPAN project 高校生の服購入店舗調査",
    sourceKind: "survey",
    purchaseUrl: "https://www.gu-global.com/jp/ja/women/skirt",
    purchaseLabel: "GU公式スカートへ",
    seller: "GU公式オンラインストア",
    priceText: "公式ページで確認",
    popularityScore: 84,
    publishedAt: "2023-09-08",
    tags: ["スカート", "高校生女子", "GU"],
  },
  {
    id: "gu-bags",
    name: "GU バッグ",
    brand: "GU",
    collections: ["accessories", "teen", "japan_brands"],
    subcategory: "bag",
    subcategoryLabel: "バッグ",
    description:
      "GU公式のバッグカテゴリ。高校生調査で支持された店舗の、公式オンラインで買えるバッグです。スクール〜放課後用のバッグを公式ページから探せます。",
    imageUrl: "/products/gu-bags.svg",
    accent: "#efe8de",
    celebrityName: null,
    celebrityRelation: null,
    sourceUrl: "https://prtimes.jp/main/html/rd/p/000000027.000118654.html",
    sourceTitle: "PR TIMES「高校生が服を購入するお店ランキング」（YTJP調査）",
    sourceKind: "survey",
    purchaseUrl: "https://www.gu-global.com/jp/ja/women/goods/bag",
    purchaseLabel: "GU公式バッグへ",
    seller: "GU公式オンラインストア",
    priceText: "公式ページで確認",
    popularityScore: 82,
    publishedAt: "2025-09-24",
    tags: ["バッグ", "高校生", "GU", "アクセサリー"],
  },
  {
    id: "converse-all-star-j-ox",
    name: "CANVAS ALL STAR J OX",
    brand: "CONVERSE",
    collections: ["fashion", "accessories", "teen", "japan_brands"],
    subcategory: "sneakers",
    subcategoryLabel: "スニーカー",
    description:
      "日本製のオールスター オックス。放課後・ストリートの定番スニーカーとして公式ショップで販売されています。高校生店舗調査のユニクロ/GU人気とあわせ、公式で買える靴の代表例として掲載しています。",
    imageUrl: "/products/converse-all-star-j-ox.svg",
    accent: "#f5f5f3",
    celebrityName: null,
    celebrityRelation: null,
    sourceUrl: "https://converse.co.jp/collections/japan",
    sourceTitle: "CONVERSE MADE IN JAPAN",
    sourceKind: "brand_official",
    purchaseUrl: "https://converse.co.jp/products/32167710",
    purchaseLabel: "コンバース公式へ",
    seller: "CONVERSE オンラインショップ",
    priceText: "15,950円（税込）",
    popularityScore: 87,
    publishedAt: "2025-01-01",
    tags: ["スニーカー", "靴", "高校生", "オールスター"],
  },
  {
    id: "shiro-savon-edp",
    name: "サボン オードパルファン",
    brand: "SHIRO",
    collections: ["fragrance", "japan_brands", "trending", "teen"],
    subcategory: "edp",
    subcategoryLabel: "オードパルファン",
    description:
      "石けんの清潔感をイメージしたSHIROの代表香。公式が「SHIRO FRAGRANCEで最も人気の高い香り」と案内しています。10代〜幅広い層向けの日本ブランド香水です。",
    scentNotes: "レモン / オレンジ / ブラックカラント / 石けんの清潔感",
    imageUrl: "/products/shiro-savon-edp.svg",
    accent: "#f6f3ee",
    celebrityName: null,
    celebrityRelation: null,
    sourceUrl: "https://shiro-shiro.jp/item/12702.html",
    sourceTitle: "SHIRO公式「サボン オードパルファン」",
    sourceKind: "brand_official",
    purchaseUrl: "https://shiro-shiro.jp/ec/pro/disp/1/12702",
    purchaseLabel: "SHIRO公式へ",
    seller: "SHIRO 公式オンラインストア",
    priceText: "4,180円（税込）/ 40mL",
    popularityScore: 90,
    publishedAt: "2025-01-01",
    tags: ["香水", "コロン", "ボディミスト姉妹品", "日本ブランド", "SHIRO"],
  },
  {
    id: "canmake-marshmallow-powder",
    name: "マシュマロフィニッシュパウダー",
    brand: "CANMAKE",
    collections: ["beauty", "japan_brands", "teen"],
    subcategory: "makeup",
    subcategoryLabel: "コスメ",
    description:
      "ドラッグストアで買えるCANMAKEのフェイスパウダー。公式商品ページで成分・使い方が確認できます。高校生調査のプチプラ店舗人気と重なる価格帯の日本コスメです。",
    imageUrl: "/products/canmake-marshmallow-powder.svg",
    accent: "#fdeef2",
    celebrityName: null,
    celebrityRelation: null,
    sourceUrl: "https://www.canmake.com/item/detail/marshmallow-finish-powder/",
    sourceTitle: "CANMAKE公式「マシュマロフィニッシュパウダー」",
    sourceKind: "brand_official",
    purchaseUrl: "https://www.cosme.com/products/detail.php?product_id=29775",
    purchaseLabel: "@cosme SHOPPINGへ",
    seller: "@cosme SHOPPING（正規販売）",
    priceText: "公式・販売ページで確認",
    popularityScore: 85,
    publishedAt: "2024-01-01",
    tags: ["コスメ", "パウダー", "高校生", "キャンメイク"],
  },
];
