import { normalizeBrand, normalizeProductName, sourceDomain } from "@/lib/discovery/normalize";
import type { DiscoveryProduct } from "@/lib/discovery/types";

const NOW = "2026-08-01T00:00:00.000Z";

function product(partial: DiscoveryProduct): DiscoveryProduct {
  return {
    ...partial,
    normalizedBrand: normalizeBrand(partial.brand),
    normalizedProductName: normalizeProductName(partial.productName),
  };
}

export const WORLD_SEED_PRODUCTS: DiscoveryProduct[] = [
  product({
    id: "prada-paradoxe-edp",
    brand: "PRADA",
    productName: "Paradoxe Eau de Parfum",
    category: "fragrance",
    subcategory: "EDP",
    country: "IT",
    description:
      "Floral ambery Prada Paradoxe EDP. The official campaign features Emma Watson. Relation is featured, not a personal-use claim.",
    productImageUrl: "/products/prada-paradoxe.svg",
    productUrl: "https://www.prada.com/ww/en/p/paradoxe-edp-50-ml/1A1351_2HDZ_F0Z99_P_ML050",
    officialUrl: "https://www.prada.com/gb/en/pradasphere/fragrances/paradoxe.html",
    price: null,
    currency: "EUR",
    sku: "1A1351_2HDZ_F0Z99_P_ML050",
    trendScore: 91,
    confidenceScore: 86,
    discoverySource: "editorial",
    status: "pending",
    normalizedBrand: "",
    normalizedProductName: "",
    trendTags: ["world_trend", "trending", "luxury", "celebrity_pick"],
    sources: [
      {
        id: "prada-paradoxe-edp-src-1",
        sourceType: "brand_official",
        sourceUrl: "https://www.prada.com/gb/en/pradasphere/fragrances/paradoxe.html",
        sourceTitle: "PRADA Paradoxe",
        sourceDomain: sourceDomain("https://www.prada.com/gb/en/pradasphere/fragrances/paradoxe.html"),
        publishedAt: "2026-01-01",
        sourceExcerpt: "Official Paradoxe fragrance story and campaign.",
        verificationStatus: "verified",
        sourceTier: 1,
        createdAt: NOW,
      },
    ],
    people: [
      {
        id: "prada-paradoxe-edp-person-1",
        personName: "Emma Watson",
        personType: "celebrity",
        personUrl: "https://www.prada.com/gb/en/pradasphere/fragrances/paradoxe.html",
        personImageUrl: null,
        relation: "featured",
        sourceId: "prada-paradoxe-edp-src-1",
        createdAt: NOW,
      },
    ],
    sales: [
      {
        id: "prada-paradoxe-edp-sale-1",
        sellerName: "PRADA",
        productUrl: "https://www.prada.com/ww/en/p/paradoxe-edp-50-ml/1A1351_2HDZ_F0Z99_P_ML050",
        price: null,
        currency: "EUR",
        availability: "unknown",
        officialStore: true,
        sellerKind: "official",
        affiliateUrl: null,
        lastVerifiedAt: NOW,
        createdAt: NOW,
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  }),
  product({
    id: "adidas-samba-og",
    brand: "adidas",
    productName: "Samba OG",
    category: "fashion",
    subcategory: "Sneakers",
    country: "DE",
    description: "adidas Samba OG, listed on the official adidas store as a current lifestyle sneaker.",
    productImageUrl: "/products/adidas-samba-og.svg",
    productUrl: "https://www.adidas.com/us/samba-og-shoes/B75807.html",
    officialUrl: "https://www.adidas.com/us/samba-og-shoes/B75807.html",
    price: null,
    currency: "USD",
    sku: "B75807",
    trendScore: 88,
    confidenceScore: 80,
    discoverySource: "editorial",
    status: "pending",
    normalizedBrand: "",
    normalizedProductName: "",
    trendTags: ["world_trend", "viral", "gen_z_trend", "streetwear", "us_trend"],
    sources: [
      {
        id: "adidas-samba-og-src-1",
        sourceType: "brand_official",
        sourceUrl: "https://www.adidas.com/us/samba-og-shoes/B75807.html",
        sourceTitle: "adidas Samba OG Shoes",
        sourceDomain: "adidas.com",
        publishedAt: null,
        sourceExcerpt: null,
        verificationStatus: "verified",
        sourceTier: 1,
        createdAt: NOW,
      },
    ],
    people: [],
    sales: [
      {
        id: "adidas-samba-og-sale-1",
        sellerName: "adidas",
        productUrl: "https://www.adidas.com/us/samba-og-shoes/B75807.html",
        price: null,
        currency: "USD",
        availability: "unknown",
        officialStore: true,
        sellerKind: "official",
        affiliateUrl: null,
        lastVerifiedAt: NOW,
        createdAt: NOW,
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  }),
  product({
    id: "cosrx-snail-96",
    brand: "COSRX",
    productName: "Advanced Snail 96 Mucin Power Essence",
    category: "beauty",
    subcategory: "Essence",
    country: "KR",
    description: "Korean essence listed on the COSRX official shop. No celebrity-use claim.",
    productImageUrl: "/products/cosrx-snail-96.svg",
    productUrl: "https://www.cosrx.com/products/advanced-snail-96-mucin-power-essence",
    officialUrl: "https://www.cosrx.com/products/advanced-snail-96-mucin-power-essence",
    price: null,
    currency: "USD",
    sku: null,
    trendScore: 84,
    confidenceScore: 75,
    discoverySource: "editorial",
    status: "pending",
    normalizedBrand: "",
    normalizedProductName: "",
    trendTags: ["world_trend", "korea_trend", "gen_z_trend", "viral", "best_seller"],
    sources: [
      {
        id: "cosrx-snail-96-src-1",
        sourceType: "brand_official",
        sourceUrl: "https://www.cosrx.com/products/advanced-snail-96-mucin-power-essence",
        sourceTitle: "COSRX Advanced Snail 96 Mucin Power Essence",
        sourceDomain: "cosrx.com",
        publishedAt: null,
        sourceExcerpt: null,
        verificationStatus: "verified",
        sourceTier: 1,
        createdAt: NOW,
      },
    ],
    people: [],
    sales: [
      {
        id: "cosrx-snail-96-sale-1",
        sellerName: "COSRX",
        productUrl: "https://www.cosrx.com/products/advanced-snail-96-mucin-power-essence",
        price: null,
        currency: "USD",
        availability: "unknown",
        officialStore: true,
        sellerKind: "official",
        affiliateUrl: null,
        lastVerifiedAt: NOW,
        createdAt: NOW,
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  }),
  product({
    id: "apple-airpods-pro-2",
    brand: "Apple",
    productName: "AirPods Pro 2",
    category: "tech",
    subcategory: "Audio",
    country: "US",
    description: "Apple AirPods Pro, listed on Apple's official product and shopping pages.",
    productImageUrl: "/products/apple-airpods-pro-2.svg",
    productUrl: "https://www.apple.com/shop/buy-airpods/airpods-pro-2",
    officialUrl: "https://www.apple.com/airpods-pro/",
    price: null,
    currency: "USD",
    sku: null,
    trendScore: 89,
    confidenceScore: 90,
    discoverySource: "editorial",
    status: "pending",
    normalizedBrand: "",
    normalizedProductName: "",
    trendTags: ["world_trend", "us_trend", "best_seller", "trending"],
    sources: [
      {
        id: "apple-airpods-pro-2-src-1",
        sourceType: "brand_official",
        sourceUrl: "https://www.apple.com/airpods-pro/",
        sourceTitle: "AirPods Pro - Apple",
        sourceDomain: "apple.com",
        publishedAt: null,
        sourceExcerpt: null,
        verificationStatus: "verified",
        sourceTier: 1,
        createdAt: NOW,
      },
    ],
    people: [],
    sales: [
      {
        id: "apple-airpods-pro-2-sale-1",
        sellerName: "Apple",
        productUrl: "https://www.apple.com/shop/buy-airpods/airpods-pro-2",
        price: null,
        currency: "USD",
        availability: "unknown",
        officialStore: true,
        sellerKind: "official",
        affiliateUrl: null,
        lastVerifiedAt: NOW,
        createdAt: NOW,
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  }),
  product({
    id: "stanley-quencher-40",
    brand: "Stanley",
    productName: "Quencher H2.0 FlowState Tumbler",
    category: "lifestyle",
    subcategory: "Drinkware",
    country: "US",
    description: "Stanley Quencher tumbler collection on the official Stanley 1913 shop. No person-use claim.",
    productImageUrl: "/products/stanley-quencher.svg",
    productUrl: "https://www.stanley1913.com/collections/quencher",
    officialUrl: "https://www.stanley1913.com/collections/quencher",
    price: null,
    currency: "USD",
    sku: null,
    trendScore: 82,
    confidenceScore: 70,
    discoverySource: "editorial",
    status: "pending",
    normalizedBrand: "",
    normalizedProductName: "",
    trendTags: ["world_trend", "viral", "gen_z_trend", "us_trend"],
    sources: [
      {
        id: "stanley-quencher-40-src-1",
        sourceType: "brand_official",
        sourceUrl: "https://www.stanley1913.com/collections/quencher",
        sourceTitle: "Stanley Quencher Collection",
        sourceDomain: "stanley1913.com",
        publishedAt: null,
        sourceExcerpt: null,
        verificationStatus: "verified",
        sourceTier: 1,
        createdAt: NOW,
      },
    ],
    people: [],
    sales: [
      {
        id: "stanley-quencher-40-sale-1",
        sellerName: "Stanley 1913",
        productUrl: "https://www.stanley1913.com/collections/quencher",
        price: null,
        currency: "USD",
        availability: "unknown",
        officialStore: true,
        sellerKind: "official",
        affiliateUrl: null,
        lastVerifiedAt: NOW,
        createdAt: NOW,
      },
    ],
    createdAt: NOW,
    updatedAt: NOW,
  }),
];
