/** Auto-generated by scripts/prepare-jp-videos.ts — do not edit by hand. */
export type JpDemoVideoTheme =
  | "コーデ紹介"
  | "今日の服"
  | "ルックブック"
  | "GRWM"
  | "メイク"
  | "コスメ購入品"
  | "ネイル"
  | "バッグの中身"
  | "カフェ"
  | "スイーツ"
  | "旅行"
  | "推し活";

export type JpDemoVideoClip = {
  theme: JpDemoVideoTheme;
  url: string;
  hasAudio: true;
};

export const JP_DEMO_VIDEO_CLIPS: JpDemoVideoClip[] = [
  {
    "theme": "カフェ",
    "url": "https://videos.pexels.com/video-files/855281/855281-hd_1920_1080_25fps.mp4",
    "hasAudio": true
  },
  {
    "theme": "旅行",
    "url": "https://videos.pexels.com/video-files/3571264/3571264-uhd_2560_1440_30fps.mp4",
    "hasAudio": true
  },
  {
    "theme": "メイク",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/makeup-43575.mp4",
    "hasAudio": true
  },
  {
    "theme": "GRWM",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/grwm-34572.mp4",
    "hasAudio": true
  },
  {
    "theme": "コーデ紹介",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/coordinate-34563.mp4",
    "hasAudio": true
  },
  {
    "theme": "今日の服",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/outfit-34487.mp4",
    "hasAudio": true
  },
  {
    "theme": "ルックブック",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/lookbook-39876.mp4",
    "hasAudio": true
  },
  {
    "theme": "コスメ購入品",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/cosmetics-32458.mp4",
    "hasAudio": true
  },
  {
    "theme": "ネイル",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/nails-1171.mp4",
    "hasAudio": true
  },
  {
    "theme": "バッグの中身",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/bag-4303.mp4",
    "hasAudio": true
  },
  {
    "theme": "カフェ",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/cafe-1199.mp4",
    "hasAudio": true
  },
  {
    "theme": "カフェ",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/cafe-432.mp4",
    "hasAudio": true
  },
  {
    "theme": "旅行",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/travel-3247.mp4",
    "hasAudio": true
  },
  {
    "theme": "旅行",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/travel-25155.mp4",
    "hasAudio": true
  },
  {
    "theme": "推し活",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/oshi-41566.mp4",
    "hasAudio": true
  },
  {
    "theme": "コーデ紹介",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/coordinate-42214.mp4",
    "hasAudio": true
  },
  {
    "theme": "今日の服",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/outfit-4613.mp4",
    "hasAudio": true
  },
  {
    "theme": "メイク",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/makeup-34566.mp4",
    "hasAudio": true
  },
  {
    "theme": "バッグの中身",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/bag-4013.mp4",
    "hasAudio": true
  },
  {
    "theme": "ルックブック",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/lookbook-5084.mp4",
    "hasAudio": true
  },
  {
    "theme": "推し活",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/oshi-25154.mp4",
    "hasAudio": true
  },
  {
    "theme": "スイーツ",
    "url": "https://lfftfzghfjdwyyfzijte.supabase.co/storage/v1/object/public/media/demo-jp/sweets-1199.mp4",
    "hasAudio": true
  }
];
