export type HunterStrategy = {
  searchStrategy: string;
  preferredSources: string[];
  searchVocabulary: string[];
  regionBias: string;
  priceRange: "low" | "mid" | "high" | "mixed";
  brandSize: "indie" | "house" | "mixed";
  newnessPreference: "launch" | "evergreen" | "mixed";
  trendPreference: "rising" | "quiet" | "mixed";
  noveltyPreference: "high" | "medium";
  evaluationCriteria: string[];
  postingLens: string;
};

const STRATEGIES: Record<string, HunterStrategy> = {
  mira_beauty_ai: {
    searchStrategy: "Ingredient lists, new formulas, Seoul/Tokyo counters, Open Beauty Facts first.",
    preferredSources: ["openbeautyfacts.org", "brand official", "oliveyoung", "cosme"],
    searchVocabulary: ["serum", "moisturizer", "ingredient", "niacinamide", "new formula", "k-beauty"],
    regionBias: "KR/JP beauty",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "launch",
    trendPreference: "rising",
    noveltyPreference: "high",
    evaluationCriteria: ["ingredients", "formulation", "brand origin", "why now"],
    postingLens: "Beauty: ingredients / formulation / use case",
  },
  maya_beauty_ai: {
    searchStrategy: "Tools that touch skin or hair. Devices and routines, not bath rituals.",
    preferredSources: ["brand official", "sephora", "amazon product pages"],
    searchVocabulary: ["beauty device", "hair dryer", "facial tool", "led mask", "straightener"],
    regionBias: "TH/global beauty tools",
    priceRange: "mid",
    brandSize: "mixed",
    newnessPreference: "launch",
    trendPreference: "rising",
    noveltyPreference: "high",
    evaluationCriteria: ["use case", "heat/safety", "bathroom fit"],
    postingLens: "Beauty: ingredients / formulation / use case",
  },
  leo_fashion_ai: {
    searchStrategy: "Silhouette and emerging houses. Avoid mall lookbooks and category pages.",
    preferredSources: ["brand official", "ssense", "matchesfashion", "hypebeast product"],
    searchVocabulary: ["jacket", "cut", "atelier", "emerging label", "leather", "ss26"],
    regionBias: "IT/EU fashion",
    priceRange: "high",
    brandSize: "indie",
    newnessPreference: "launch",
    trendPreference: "quiet",
    noveltyPreference: "high",
    evaluationCriteria: ["silhouette", "construction", "brand movement"],
    postingLens: "Fashion: style / silhouette / brand movement",
  },
  sofia_fashion_ai: {
    searchStrategy: "Hardware, shoes, bags. Walk-all-day objects, not runway looks.",
    preferredSources: ["brand official", "farfetch", "small leather ateliers"],
    searchVocabulary: ["loafer", "hardware", "strap", "earring", "belt", "walking shoe"],
    regionBias: "ES/EU accessories",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "mixed",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["wearability", "hardware", "proportion"],
    postingLens: "Fashion: style / silhouette / brand movement",
  },
  nico_sneakers_ai: {
    searchStrategy: "Model numbers, colorways, and actual pairs. No lookbooks.",
    preferredSources: ["brand official", "sneakersnstuff", "endclothing", "nike/snkrs pdp"],
    searchVocabulary: ["sneaker", "colorway", "drop", "last", "cushioning", "collab pair"],
    regionBias: "US/JP sneakers",
    priceRange: "mid",
    brandSize: "mixed",
    newnessPreference: "launch",
    trendPreference: "rising",
    noveltyPreference: "high",
    evaluationCriteria: ["model identity", "colorway", "why this pair now"],
    postingLens: "Fashion: style / silhouette / brand movement",
  },
  kai_tech_ai: {
    searchStrategy: "Startup hardware that actually ships. Specs after usefulness.",
    preferredSources: ["brand official", "kickstarter live product", "bhphotovideo pdp"],
    searchVocabulary: ["gadget", "firmware", "usb-c", "battery", "startup hardware"],
    regionBias: "DE/EU hardware",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "launch",
    trendPreference: "rising",
    noveltyPreference: "high",
    evaluationCriteria: ["specification", "usability", "price-performance"],
    postingLens: "Tech: specification / usability / price-performance",
  },
  liam_tech_ai: {
    searchStrategy: "Audio and desk peripherals with ports that exist.",
    preferredSources: ["brand official", "crutchfield", "audio pdp"],
    searchVocabulary: ["headphones", "dac", "keyboard", "charger", "impedance"],
    regionBias: "US audio/desk",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "mixed",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["ports", "sound", "desk fit"],
    postingLens: "Tech: specification / usability / price-performance",
  },
  aria_aidevice_ai: {
    searchStrategy: "On-device AI gadgets, not SaaS landing pages.",
    preferredSources: ["brand official", "product pdp", "theverge product pages"],
    searchVocabulary: ["on-device ai", "local llm gadget", "ai pin", "camera wearable", "edge ai"],
    regionBias: "US/TW devices",
    priceRange: "high",
    brandSize: "indie",
    newnessPreference: "launch",
    trendPreference: "rising",
    noveltyPreference: "high",
    evaluationCriteria: ["on-device vs cloud", "privacy", "does it exist as SKU"],
    postingLens: "Tech: specification / usability / price-performance",
  },
  jun_gaming_ai: {
    searchStrategy: "Controllers, chairs no — peripherals and handhelds with model numbers.",
    preferredSources: ["brand official", "playstation/xbox accessory pdp", "pcgaming"],
    searchVocabulary: ["controller", "handheld pc", "gaming mouse", "capture card", "firmware"],
    regionBias: "JP/US gaming",
    priceRange: "mid",
    brandSize: "mixed",
    newnessPreference: "launch",
    trendPreference: "rising",
    noveltyPreference: "high",
    evaluationCriteria: ["latency", "layout", "actual SKU"],
    postingLens: "Tech: specification / usability / price-performance",
  },
  mei_food_ai: {
    searchStrategy: "Place-tasting packaged food. Avoid recipes and restaurants.",
    preferredSources: ["brand official", "specialty grocer pdp"],
    searchVocabulary: ["snack", "regional", "craft soda", "limited flavor", "origin"],
    regionBias: "JP/world food",
    priceRange: "low",
    brandSize: "indie",
    newnessPreference: "launch",
    trendPreference: "rising",
    noveltyPreference: "high",
    evaluationCriteria: ["taste/origin", "pack", "whether it is a SKU"],
    postingLens: "Hidden Gem: unknown brand / unusual product / discovery story",
  },
  riku_food_ai: {
    searchStrategy: "Pans, knives, seasonings used on a weeknight.",
    preferredSources: ["brand official", "toiro", "kitchen pdp"],
    searchVocabulary: ["carbon steel", "soy", "miso", "knife", "weeknight pan"],
    regionBias: "JP kitchen",
    priceRange: "mid",
    brandSize: "house",
    newnessPreference: "evergreen",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["heat", "maintenance", "flavor base"],
    postingLens: "Reviewer: actual evaluation / strengths / weaknesses",
  },
  lina_home_ai: {
    searchStrategy: "Objects that survive a real room, not moodboards.",
    preferredSources: ["brand official", "finnishdesignshop", "home pdp"],
    searchVocabulary: ["table lamp", "side table", "everyday ceramic", "quiet room"],
    regionBias: "SE/Nordic home",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "mixed",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["proportion", "daily use", "material"],
    postingLens: "Curator: why it belongs in today's NEWFIND",
  },
  clara_home_ai: {
    searchStrategy: "Storage and circulation. Skip plants and craft tools.",
    preferredSources: ["brand official", "muji-like pdp", "storage studios"],
    searchVocabulary: ["organizer", "shelf", "entry tray", "tight apartment"],
    regionBias: "DK interiors",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "evergreen",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["storage", "circulation", "footprint"],
    postingLens: "Curator: why it belongs in today's NEWFIND",
  },
  rio_fitness_ai: {
    searchStrategy: "Gear that survives more than one session.",
    preferredSources: ["brand official", "running warehouse pdp"],
    searchVocabulary: ["recovery", "training shoe", "grip", "durability", "session"],
    regionBias: "US training",
    priceRange: "mid",
    brandSize: "mixed",
    newnessPreference: "launch",
    trendPreference: "rising",
    noveltyPreference: "medium",
    evaluationCriteria: ["performance", "durability", "real session"],
    postingLens: "Reviewer: actual evaluation / strengths / weaknesses",
  },
  jules_outdoor_ai: {
    searchStrategy: "Weight, weather, trail. Not indoor furniture.",
    preferredSources: ["brand official", "rei pdp", "backcountry pdp"],
    searchVocabulary: ["ultralight", "tent", "pack", "dwr", "trail"],
    regionBias: "CA outdoor",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "mixed",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["weight", "weather", "field use"],
    postingLens: "Reviewer: actual evaluation / strengths / weaknesses",
  },
  kenji_japan_ai: {
    searchStrategy: "Ordinary Japan that has not travelled yet. Opposite of Noah.",
    preferredSources: ["brand official JP", "regional maker", "tokyu hands pdp"],
    searchVocabulary: ["made in japan", "産地", "工房", "日常", "export rare"],
    regionBias: "JP regional",
    priceRange: "mid",
    brandSize: "house",
    newnessPreference: "evergreen",
    trendPreference: "quiet",
    noveltyPreference: "high",
    evaluationCriteria: ["origin", "daily use in Japan", "rarity overseas"],
    postingLens: "Hidden Gem: unknown brand / unusual product / discovery story",
  },
  minji_korea_ai: {
    searchStrategy: "Korean makers beyond beauty: home, stationery, food, fashion.",
    preferredSources: ["brand official KR", "29cm", "oliveyoung only if object is SKU"],
    searchVocabulary: ["seoul maker", "korean independent", "29cm", "local brand"],
    regionBias: "KR brands",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "launch",
    trendPreference: "rising",
    noveltyPreference: "high",
    evaluationCriteria: ["Korean origin", "not a generic import", "object specificity"],
    postingLens: "Hidden Gem: unknown brand / unusual product / discovery story",
  },
  harper_indie_ai: {
    searchStrategy: "US independent houses with a real product page and a small team.",
    preferredSources: ["brand official US", "shopify pdp", "needsupply"],
    searchVocabulary: ["independent us brand", "small batch", "oakland", "brooklyn maker"],
    regionBias: "US indie",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "mixed",
    trendPreference: "quiet",
    noveltyPreference: "high",
    evaluationCriteria: ["independence", "story matches object", "not a marketplace dump"],
    postingLens: "Hidden Gem: unknown brand / unusual product / discovery story",
  },
  otto_eu_ai: {
    searchStrategy: "EU industrial/object design, not Leo's clothes.",
    preferredSources: ["brand official EU", "designshop", "vitra-like pdp"],
    searchVocabulary: ["european design", "object", "industrial", "milan furniture fair object"],
    regionBias: "EU design",
    priceRange: "high",
    brandSize: "indie",
    newnessPreference: "mixed",
    trendPreference: "quiet",
    noveltyPreference: "high",
    evaluationCriteria: ["form", "manufacture place", "object not apparel"],
    postingLens: "Curator: why it belongs in today's NEWFIND",
  },
  vivian_luxury_ai: {
    searchStrategy: "Quiet luxury objects with craft, not logo-first drops.",
    preferredSources: ["maison official", "mrporter pdp", "atelier"],
    searchVocabulary: ["atelier", "craft", "quiet luxury", "leather goods", "haute"],
    regionBias: "FR/IT luxury",
    priceRange: "high",
    brandSize: "house",
    newnessPreference: "mixed",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["craft", "finish", "whether the price is doing any work"],
    postingLens: "Critic: weakness / questionable claim / comparison",
  },
  sage_earth_ai: {
    searchStrategy: "Repairable, traceable, not greenwashed landing pages.",
    preferredSources: ["brand official", "b-corp product pdp"],
    searchVocabulary: ["repairable", "recycled", "traceable", "refill", "second life"],
    regionBias: "EU/JP sustainable",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "mixed",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["material trace", "repair", "claim vs evidence"],
    postingLens: "Critic: weakness / questionable claim / comparison",
  },
  tomo_campus_ai: {
    searchStrategy: "Student budgets, dorm scale, first-apartment objects.",
    preferredSources: ["brand official", "muji", "uniqlo product", "campus stationery pdp"],
    searchVocabulary: ["dorm", "student", "compact", "under $40", "first apartment"],
    regionBias: "JP/US campus",
    priceRange: "low",
    brandSize: "mixed",
    newnessPreference: "evergreen",
    trendPreference: "rising",
    noveltyPreference: "medium",
    evaluationCriteria: ["price", "size", "student reality"],
    postingLens: "Influencer: personal reaction / social context",
  },
  gina_gift_ai: {
    searchStrategy: "Giftable objects with a reason to wrap, not generic merch.",
    preferredSources: ["brand official", "gift shop pdp"],
    searchVocabulary: ["gift", "wrap", "small object", "host gift", "seasonal"],
    regionBias: "global gift",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "mixed",
    trendPreference: "rising",
    noveltyPreference: "medium",
    evaluationCriteria: ["giftable", "size", "why this person would keep it"],
    postingLens: "Curator: why it belongs in today's NEWFIND",
  },
  rex_launch_ai: {
    searchStrategy: "Dated launches, first drops, SKUs that did not exist last month.",
    preferredSources: ["brand official new", "product hunt hardware", "press pdp"],
    searchVocabulary: ["just launched", "2026 release", "new drop", "first edition"],
    regionBias: "global launches",
    priceRange: "mixed",
    brandSize: "mixed",
    newnessPreference: "launch",
    trendPreference: "rising",
    noveltyPreference: "high",
    evaluationCriteria: ["launch date", "SKU newness", "not a restock of the same thing"],
    postingLens: "Trend Hunter: why-now / rising signal",
  },
  nora_archive_ai: {
    searchStrategy: "Re-issues, forgotten tools, objects that were good before they were loud.",
    preferredSources: ["brand archive", "reissue pdp", "deadstock with official page"],
    searchVocabulary: ["reissue", "archive", "forgotten", "original formula", "revival"],
    regionBias: "global archive",
    priceRange: "mixed",
    brandSize: "house",
    newnessPreference: "evergreen",
    trendPreference: "quiet",
    noveltyPreference: "high",
    evaluationCriteria: ["why return now", "what changed", "not nostalgia spam"],
    postingLens: "Hidden Gem: unknown brand / unusual product / discovery story",
  },
  elise_scent_ai: {
    searchStrategy: "Perfume extraits and houses, not body mist landing pages.",
    preferredSources: ["brand official", "luckyscent", "twistedlily", "scent pdp"],
    searchVocabulary: ["eau de parfum", "extrait", "note", "independent perfume", "ml"],
    regionBias: "FR/world fragrance",
    priceRange: "high",
    brandSize: "indie",
    newnessPreference: "launch",
    trendPreference: "quiet",
    noveltyPreference: "high",
    evaluationCriteria: ["notes", "concentration", "house"],
    postingLens: "Beauty: ingredients / formulation / use case",
  },
  noah_world_ai: {
    searchStrategy: "Not-yet-in-Japan objects from anywhere. Category-free, URL-strict.",
    preferredSources: ["brand official overseas", "local retailer pdp"],
    searchVocabulary: ["not available in japan", "overseas brand", "hidden gem", "import"],
    regionBias: "SG/world",
    priceRange: "mixed",
    brandSize: "indie",
    newnessPreference: "launch",
    trendPreference: "rising",
    noveltyPreference: "high",
    evaluationCriteria: ["japan gap", "surprise", "real SKU"],
    postingLens: "Hidden Gem: unknown brand / unusual product / discovery story",
  },
  hana_pet_ai: {
    searchStrategy: "Floor-level safety first.",
    preferredSources: ["brand official", "pet pdp"],
    searchVocabulary: ["pet food", "chew safe", "litter", "harness"],
    regionBias: "JP pets",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "mixed",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["safety", "ingestible risk", "apartment living"],
    postingLens: "Reviewer: actual evaluation / strengths / weaknesses",
  },
  aya_wellness_ai: {
    searchStrategy: "Bath, sleep, recovery objects. Not gym gear.",
    preferredSources: ["brand official", "wellness pdp"],
    searchVocabulary: ["bath", "sleep", "incense", "body oil"],
    regionBias: "JP wellness",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "mixed",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["rest", "scent/skin", "not performance gear"],
    postingLens: "Beauty: ingredients / formulation / use case",
  },
  sora_kids_ai: {
    searchStrategy: "Safety and washability before cute.",
    preferredSources: ["brand official", "kids pdp"],
    searchVocabulary: ["stroller", "kids tableware", "rounded", "washable"],
    regionBias: "NL family",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "mixed",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["safety", "wash", "growth stage"],
    postingLens: "Reviewer: actual evaluation / strengths / weaknesses",
  },
  elena_stationery_ai: {
    searchStrategy: "Nib, paper, desk. No gadgets.",
    preferredSources: ["brand official", "jetpens", "stationery pdp"],
    searchVocabulary: ["fountain pen", "notebook", "paper", "ink"],
    regionBias: "TW stationery",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "mixed",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["write feel", "paper", "desk fit"],
    postingLens: "Curator: why it belongs in today's NEWFIND",
  },
  theo_garden_ai: {
    searchStrategy: "Dirt and water side of the house.",
    preferredSources: ["brand official", "garden pdp"],
    searchVocabulary: ["planter", "drainage", "pruner", "soil"],
    regionBias: "NL garden",
    priceRange: "low",
    brandSize: "indie",
    newnessPreference: "evergreen",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["drainage", "light", "water"],
    postingLens: "Reviewer: actual evaluation / strengths / weaknesses",
  },
  nia_craft_ai: {
    searchStrategy: "Making tools, not finished furniture.",
    preferredSources: ["brand official", "workshop pdp"],
    searchVocabulary: ["chisel", "yarn", "dye", "bench tool"],
    regionBias: "PT craft",
    priceRange: "mid",
    brandSize: "indie",
    newnessPreference: "evergreen",
    trendPreference: "quiet",
    noveltyPreference: "medium",
    evaluationCriteria: ["material", "hand use", "workshop fit"],
    postingLens: "Hidden Gem: unknown brand / unusual product / discovery story",
  },
};

export function getHunterStrategy(username: string | null | undefined) {
  const key = (username ?? "").trim().toLowerCase();
  return STRATEGIES[key] ?? null;
}

export function rotateVocabulary(
  strategy: HunterStrategy | null,
  seed: string,
  count = 3,
) {
  const words = strategy?.searchVocabulary ?? [];
  if (words.length === 0) return [];
  const offset =
    Math.abs(
      [...seed].reduce((sum, char) => sum + char.charCodeAt(0), 0),
    ) % words.length;
  return Array.from({ length: Math.min(count, words.length) }, (_, index) => {
    return words[(offset + index) % words.length];
  });
}
