export const WORLD_LANGUAGES = [
  "Japanese",
  "English",
  "Korean",
  "Chinese",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Hindi",
  "Arabic",
  "Dutch",
  "Swedish",
] as const;

export type WorldLanguage = (typeof WORLD_LANGUAGES)[number];

export const WORLD_EXPERTISE = [
  "technology",
  "economics",
  "business",
  "fashion",
  "beauty",
  "food",
  "science",
  "design",
  "sports",
  "gaming",
  "travel",
  "sustainability",
  "culture",
  "media",
  "finance",
  "health",
  "lifestyle",
] as const;

export type WorldExpertise = (typeof WORLD_EXPERTISE)[number];

export const WORLD_VALUES = [
  "innovation",
  "quality",
  "price-conscious",
  "sustainability",
  "craftsmanship",
  "convenience",
  "social-impact",
  "design",
  "performance",
  "brand-story",
  "local-culture",
] as const;

export type WorldValue = (typeof WORLD_VALUES)[number];

export const WORLD_ROLES = [
  "product_hunter",
  "influencer",
  "reviewer",
  "fan",
  "critic",
  "media",
  "general_user",
  "trend_hunter",
  "curator",
] as const;

export type WorldRole = (typeof WORLD_ROLES)[number];

export const TEMPERAMENTS = [
  "curious",
  "calm",
  "sharp",
  "warm",
  "analytical",
  "playful",
  "meticulous",
  "bold",
  "reserved",
  "optimistic",
] as const;

export type Temperament = (typeof TEMPERAMENTS)[number];

export const BEHAVIORS = [
  "explorer",
  "observer",
  "connector",
  "collector",
  "editor",
  "skeptic",
  "early_adopter",
  "loyalist",
] as const;

export type BehaviorPattern = (typeof BEHAVIORS)[number];

export const PRODUCT_TASTES = [
  "minimal",
  "artisan",
  "tech-forward",
  "quiet-luxury",
  "practical",
  "playful",
  "vintage",
  "experimental",
  "premium-everyday",
  "outdoor",
] as const;

export type ProductTaste = (typeof PRODUCT_TASTES)[number];

export const EXTRA_INTERESTS = [
  "coffee",
  "ceramics",
  "sneakers",
  "perfume",
  "watches",
  "photography",
  "street-food",
  "architecture",
  "skincare",
  "vinyl",
  "cycling",
  "hiking",
  "indie-games",
  "stationery",
  "home-cooking",
  "museums",
  "yoga",
  "film",
  "gardening",
  "baking",
  "climbing",
  "tea",
  "camping",
  "interior",
  "books",
  "running",
  "pottery",
  "jazz",
  "sneakers-culture",
  "secondhand",
] as const;

export type NamePart = {
  native: string;
  roman: string;
};

export type RegionProfile = {
  id: string;
  countryCode: string;
  region: string;
  culture: string;
  nameOrder: "given-family" | "family-given";
  defaultLanguages: WorldLanguage[];
  givenNames: NamePart[];
  familyNames: NamePart[];
  countryCodeVariants?: string[];
};

export const WORLD_REGIONS: RegionProfile[] = [
  {
    id: "japan",
    countryCode: "JP",
    region: "Japan",
    culture: "seasonal living, craftsmanship, and care in everyday objects",
    nameOrder: "family-given",
    defaultLanguages: ["Japanese", "English"],
    givenNames: [
      { native: "結衣", roman: "yui" },
      { native: "陽菜", roman: "hina" },
      { native: "美月", roman: "mizuki" },
      { native: "蓮", roman: "ren" },
      { native: "颯真", roman: "soma" },
      { native: "凛", roman: "rin" },
      { native: "直樹", roman: "naoki" },
      { native: "恵", roman: "megumi" },
      { native: "智也", roman: "tomoya" },
      { native: "咲良", roman: "sakura" },
      { native: "大和", roman: "yamato" },
      { native: "琴音", roman: "kotone" },
      { native: "隼人", roman: "hayato" },
      { native: "紬", roman: "tsumugi" },
      { native: "悠真", roman: "yuma" },
      { native: "葵", roman: "aoi" },
    ],
    familyNames: [
      { native: "佐藤", roman: "sato" },
      { native: "鈴木", roman: "suzuki" },
      { native: "高橋", roman: "takahashi" },
      { native: "田中", roman: "tanaka" },
      { native: "伊藤", roman: "ito" },
      { native: "渡辺", roman: "watanabe" },
      { native: "山本", roman: "yamamoto" },
      { native: "中村", roman: "nakamura" },
      { native: "小林", roman: "kobayashi" },
      { native: "加藤", roman: "kato" },
      { native: "吉田", roman: "yoshida" },
      { native: "山田", roman: "yamada" },
    ],
  },
  {
    id: "south_korea",
    countryCode: "KR",
    region: "South Korea",
    culture: "fast culture cycles, beauty craft, and precise everyday design",
    nameOrder: "family-given",
    defaultLanguages: ["Korean", "English"],
    givenNames: [
      { native: "민준", roman: "minjun" },
      { native: "서연", roman: "seoyeon" },
      { native: "하준", roman: "hajun" },
      { native: "지유", roman: "jiyu" },
      { native: "도윤", roman: "doyun" },
      { native: "서윤", roman: "seoyoon" },
      { native: "은우", roman: "eunwoo" },
      { native: "하은", roman: "haeun" },
      { native: "주원", roman: "juwon" },
      { native: "지안", roman: "jian" },
      { native: "시우", roman: "siwoo" },
      { native: "채원", roman: "chaewon" },
      { native: "연우", roman: "yeonwoo" },
      { native: "수아", roman: "sua" },
      { native: "건우", roman: "gunwoo" },
      { native: "예린", roman: "yerin" },
    ],
    familyNames: [
      { native: "김", roman: "kim" },
      { native: "이", roman: "lee" },
      { native: "박", roman: "park" },
      { native: "최", roman: "choi" },
      { native: "정", roman: "jung" },
      { native: "강", roman: "kang" },
      { native: "조", roman: "cho" },
      { native: "윤", roman: "yoon" },
      { native: "장", roman: "jang" },
      { native: "임", roman: "lim" },
      { native: "한", roman: "han" },
      { native: "오", roman: "oh" },
    ],
  },
  {
    id: "china",
    countryCode: "CN",
    region: "China",
    culture: "scale, craft lineages, and new consumer aesthetics",
    nameOrder: "family-given",
    defaultLanguages: ["Chinese", "English"],
    givenNames: [
      { native: "一辰", roman: "yichen" },
      { native: "诗涵", roman: "shihan" },
      { native: "浩然", roman: "haoran" },
      { native: "雨桐", roman: "yutong" },
      { native: "子轩", roman: "zixuan" },
      { native: "佳怡", roman: "jiayi" },
      { native: "明杰", roman: "mingjie" },
      { native: "欣怡", roman: "xinyi" },
      { native: "天佑", roman: "tianyou" },
      { native: "梦琪", roman: "mengqi" },
      { native: "俊豪", roman: "junhao" },
      { native: "晓燕", roman: "xiaoyan" },
      { native: "志强", roman: "zhiqiang" },
      { native: "雪怡", roman: "xueyi" },
      { native: "嘉伟", roman: "jiawei" },
      { native: "美玲", roman: "meiling" },
    ],
    familyNames: [
      { native: "王", roman: "wang" },
      { native: "李", roman: "li" },
      { native: "张", roman: "zhang" },
      { native: "刘", roman: "liu" },
      { native: "陈", roman: "chen" },
      { native: "杨", roman: "yang" },
      { native: "黄", roman: "huang" },
      { native: "赵", roman: "zhao" },
      { native: "吴", roman: "wu" },
      { native: "周", roman: "zhou" },
      { native: "徐", roman: "xu" },
      { native: "孙", roman: "sun" },
    ],
  },
  {
    id: "taiwan",
    countryCode: "TW",
    region: "Taiwan",
    culture: "cafe culture, design detail, and warm local independent brands",
    nameOrder: "family-given",
    defaultLanguages: ["Chinese", "English"],
    givenNames: [
      { native: "品妤", roman: "pinyu" },
      { native: "承恩", roman: "chengen" },
      { native: "思颖", roman: "suying" },
      { native: "柏翰", roman: "bohan" },
      { native: "宜臻", roman: "yichen" },
      { native: "冠宇", roman: "guanyu" },
      { native: "雅婷", roman: "yating" },
      { native: "俊杰", roman: "junjie" },
      { native: "心怡", roman: "xinyi" },
      { native: "家豪", roman: "jiahao" },
      { native: "诗婷", roman: "shiting" },
      { native: "宗翰", roman: "zonghan" },
      { native: "于晴", roman: "yuqing" },
      { native: "建宏", roman: "jianhong" },
      { native: "佩珊", roman: "peishan" },
      { native: "志伟", roman: "zhiwei" },
    ],
    familyNames: [
      { native: "林", roman: "lin" },
      { native: "陈", roman: "chen" },
      { native: "黄", roman: "huang" },
      { native: "张", roman: "zhang" },
      { native: "李", roman: "li" },
      { native: "王", roman: "wang" },
      { native: "吴", roman: "wu" },
      { native: "刘", roman: "liu" },
      { native: "蔡", roman: "tsai" },
      { native: "杨", roman: "yang" },
      { native: "许", roman: "hsu" },
      { native: "郑", roman: "cheng" },
    ],
  },
  {
    id: "singapore",
    countryCode: "SG",
    region: "Singapore",
    culture: "multicultural city living, practical luxury, and food discovery",
    nameOrder: "given-family",
    defaultLanguages: ["English", "Chinese"],
    givenNames: [
      { native: "Marcus", roman: "marcus" },
      { native: "Aisha", roman: "aisha" },
      { native: "Wei Ming", roman: "weiming" },
      { native: "Priya", roman: "priya" },
      { native: "Chloe", roman: "chloe" },
      { native: "Hafiz", roman: "hafiz" },
      { native: "Mei Ling", roman: "meiling" },
      { native: "Daniel", roman: "daniel" },
      { native: "Siti", roman: "siti" },
      { native: "Ryan", roman: "ryan" },
      { native: "Ananya", roman: "ananya" },
      { native: "Jia Hui", roman: "jiahui" },
      { native: "Noah", roman: "noah" },
      { native: "Liyana", roman: "liyana" },
      { native: "Kenji", roman: "kenji" },
      { native: "Tara", roman: "tara" },
    ],
    familyNames: [
      { native: "Tan", roman: "tan" },
      { native: "Lim", roman: "lim" },
      { native: "Ng", roman: "ng" },
      { native: "Wong", roman: "wong" },
      { native: "Rahman", roman: "rahman" },
      { native: "Nair", roman: "nair" },
      { native: "Lee", roman: "lee" },
      { native: "Chong", roman: "chong" },
      { native: "Ong", roman: "ong" },
      { native: "Hassan", roman: "hassan" },
      { native: "Das", roman: "das" },
      { native: "Goh", roman: "goh" },
    ],
  },
  {
    id: "india",
    countryCode: "IN",
    region: "India",
    culture: "color, craft, family brands, and ambitious new consumer design",
    nameOrder: "given-family",
    defaultLanguages: ["English", "Hindi"],
    givenNames: [
      { native: "Arjun", roman: "arjun" },
      { native: "Priya", roman: "priya" },
      { native: "Kabir", roman: "kabir" },
      { native: "Ananya", roman: "ananya" },
      { native: "Rohan", roman: "rohan" },
      { native: "Isha", roman: "isha" },
      { native: "Vihaan", roman: "vihaan" },
      { native: "Meera", roman: "meera" },
      { native: "Aditya", roman: "aditya" },
      { native: "Sana", roman: "sana" },
      { native: "Dev", roman: "dev" },
      { native: "Nisha", roman: "nisha" },
      { native: "Aarav", roman: "aarav" },
      { native: "Diya", roman: "diya" },
      { native: "Karan", roman: "karan" },
      { native: "Riya", roman: "riya" },
    ],
    familyNames: [
      { native: "Sharma", roman: "sharma" },
      { native: "Patel", roman: "patel" },
      { native: "Mehta", roman: "mehta" },
      { native: "Iyer", roman: "iyer" },
      { native: "Khan", roman: "khan" },
      { native: "Reddy", roman: "reddy" },
      { native: "Nair", roman: "nair" },
      { native: "Gupta", roman: "gupta" },
      { native: "Singh", roman: "singh" },
      { native: "Das", roman: "das" },
      { native: "Joshi", roman: "joshi" },
      { native: "Kapoor", roman: "kapoor" },
    ],
  },
  {
    id: "united_states",
    countryCode: "US",
    region: "United States",
    culture: "independent brands, drops, and practical American product culture",
    nameOrder: "given-family",
    defaultLanguages: ["English", "Spanish"],
    givenNames: [
      { native: "Sofia", roman: "sofia" },
      { native: "Noah", roman: "noah" },
      { native: "Maya", roman: "maya" },
      { native: "Julian", roman: "julian" },
      { native: "Ava", roman: "ava" },
      { native: "Ethan", roman: "ethan" },
      { native: "Luna", roman: "luna" },
      { native: "Caleb", roman: "caleb" },
      { native: "Zoe", roman: "zoe" },
      { native: "Mason", roman: "mason" },
      { native: "Harper", roman: "harper" },
      { native: "Leo", roman: "leo" },
      { native: "Nora", roman: "nora" },
      { native: "Owen", roman: "owen" },
      { native: "Ivy", roman: "ivy" },
      { native: "Miles", roman: "miles" },
    ],
    familyNames: [
      { native: "Bennett", roman: "bennett" },
      { native: "Reyes", roman: "reyes" },
      { native: "Walker", roman: "walker" },
      { native: "Nguyen", roman: "nguyen" },
      { native: "Brooks", roman: "brooks" },
      { native: "Patel", roman: "patel" },
      { native: "Carter", roman: "carter" },
      { native: "Kim", roman: "kim" },
      { native: "Foster", roman: "foster" },
      { native: "Diaz", roman: "diaz" },
      { native: "Hayes", roman: "hayes" },
      { native: "Coleman", roman: "coleman" },
    ],
  },
  {
    id: "canada",
    countryCode: "CA",
    region: "Canada",
    culture: "outdoor practicality, bilingual city life, and quiet quality",
    nameOrder: "given-family",
    defaultLanguages: ["English", "French"],
    givenNames: [
      { native: "Emile", roman: "emile" },
      { native: "Chloe", roman: "chloe" },
      { native: "Liam", roman: "liam" },
      { native: "Amelia", roman: "amelia" },
      { native: "Theo", roman: "theo" },
      { native: "Camille", roman: "camille" },
      { native: "Owen", roman: "owen" },
      { native: "Sophie", roman: "sophie" },
      { native: "Nathan", roman: "nathan" },
      { native: "Clara", roman: "clara" },
      { native: "Felix", roman: "felix" },
      { native: "Maya", roman: "maya" },
      { native: "Jade", roman: "jade" },
      { native: "Elliot", roman: "elliot" },
      { native: "Lea", roman: "lea" },
      { native: "Noah", roman: "noah" },
    ],
    familyNames: [
      { native: "Tremblay", roman: "tremblay" },
      { native: "Roy", roman: "roy" },
      { native: "Gagnon", roman: "gagnon" },
      { native: "Martin", roman: "martin" },
      { native: "Chen", roman: "chen" },
      { native: "Singh", roman: "singh" },
      { native: "MacLeod", roman: "macleod" },
      { native: "Bouchard", roman: "bouchard" },
      { native: "Lee", roman: "lee" },
      { native: "Scott", roman: "scott" },
      { native: "Morin", roman: "morin" },
      { native: "Nguyen", roman: "nguyen" },
    ],
  },
  {
    id: "mexico",
    countryCode: "MX",
    region: "Mexico",
    culture: "color, craft, food, and proud local design",
    nameOrder: "given-family",
    defaultLanguages: ["Spanish", "English"],
    givenNames: [
      { native: "Camila", roman: "camila" },
      { native: "Mateo", roman: "mateo" },
      { native: "Valentina", roman: "valentina" },
      { native: "Santiago", roman: "santiago" },
      { native: "Lucia", roman: "lucia" },
      { native: "Diego", roman: "diego" },
      { native: "Renata", roman: "renata" },
      { native: "Emiliano", roman: "emiliano" },
      { native: "Maria", roman: "maria" },
      { native: "Sebastian", roman: "sebastian" },
      { native: "Ximena", roman: "ximena" },
      { native: "Leonardo", roman: "leonardo" },
      { native: "Regina", roman: "regina" },
      { native: "Joaquin", roman: "joaquin" },
      { native: "Paula", roman: "paula" },
      { native: "Iker", roman: "iker" },
    ],
    familyNames: [
      { native: "Hernandez", roman: "hernandez" },
      { native: "Garcia", roman: "garcia" },
      { native: "Martinez", roman: "martinez" },
      { native: "Lopez", roman: "lopez" },
      { native: "Gonzalez", roman: "gonzalez" },
      { native: "Perez", roman: "perez" },
      { native: "Sanchez", roman: "sanchez" },
      { native: "Ramirez", roman: "ramirez" },
      { native: "Torres", roman: "torres" },
      { native: "Flores", roman: "flores" },
      { native: "Rivera", roman: "rivera" },
      { native: "Cruz", roman: "cruz" },
    ],
  },
  {
    id: "brazil",
    countryCode: "BR",
    region: "Brazil",
    culture: "warm social energy, body-and-beauty culture, and vibrant design",
    nameOrder: "given-family",
    defaultLanguages: ["Portuguese", "English"],
    givenNames: [
      { native: "Ana", roman: "ana" },
      { native: "Lucas", roman: "lucas" },
      { native: "Beatriz", roman: "beatriz" },
      { native: "Gabriel", roman: "gabriel" },
      { native: "Larissa", roman: "larissa" },
      { native: "Rafael", roman: "rafael" },
      { native: "Mariana", roman: "mariana" },
      { native: "Thiago", roman: "thiago" },
      { native: "Isabela", roman: "isabela" },
      { native: "Pedro", roman: "pedro" },
      { native: "Camila", roman: "camila" },
      { native: "Matheus", roman: "matheus" },
      { native: "Julia", roman: "julia" },
      { native: "Bruno", roman: "bruno" },
      { native: "Fernanda", roman: "fernanda" },
      { native: "Enzo", roman: "enzo" },
    ],
    familyNames: [
      { native: "Silva", roman: "silva" },
      { native: "Santos", roman: "santos" },
      { native: "Oliveira", roman: "oliveira" },
      { native: "Souza", roman: "souza" },
      { native: "Pereira", roman: "pereira" },
      { native: "Costa", roman: "costa" },
      { native: "Rodrigues", roman: "rodrigues" },
      { native: "Almeida", roman: "almeida" },
      { native: "Nascimento", roman: "nascimento" },
      { native: "Lima", roman: "lima" },
      { native: "Araujo", roman: "araujo" },
      { native: "Carvalho", roman: "carvalho" },
    ],
  },
  {
    id: "united_kingdom",
    countryCode: "GB",
    region: "United Kingdom",
    culture: "dry humor, heritage brands, and sharp high-street observation",
    nameOrder: "given-family",
    defaultLanguages: ["English"],
    givenNames: [
      { native: "Oliver", roman: "oliver" },
      { native: "Amelia", roman: "amelia" },
      { native: "Harry", roman: "harry" },
      { native: "Isla", roman: "isla" },
      { native: "Arthur", roman: "arthur" },
      { native: "Freya", roman: "freya" },
      { native: "George", roman: "george" },
      { native: "Daisy", roman: "daisy" },
      { native: "Noah", roman: "noah" },
      { native: "Emily", roman: "emily" },
      { native: "Oscar", roman: "oscar" },
      { native: "Poppy", roman: "poppy" },
      { native: "Theo", roman: "theo" },
      { native: "Willow", roman: "willow" },
      { native: "Archie", roman: "archie" },
      { native: "Ella", roman: "ella" },
    ],
    familyNames: [
      { native: "Hughes", roman: "hughes" },
      { native: "Patel", roman: "patel" },
      { native: "Clarke", roman: "clarke" },
      { native: "Murray", roman: "murray" },
      { native: "Khan", roman: "khan" },
      { native: "Wright", roman: "wright" },
      { native: "Bennett", roman: "bennett" },
      { native: "Walsh", roman: "walsh" },
      { native: "Reid", roman: "reid" },
      { native: "Foster", roman: "foster" },
      { native: "Campbell", roman: "campbell" },
      { native: "Scott", roman: "scott" },
    ],
  },
  {
    id: "france",
    countryCode: "FR",
    region: "France",
    culture: "taste, material quality, and the story behind an object",
    nameOrder: "given-family",
    defaultLanguages: ["French", "English"],
    givenNames: [
      { native: "Camille", roman: "camille" },
      { native: "Louis", roman: "louis" },
      { native: "Lea", roman: "lea" },
      { native: "Hugo", roman: "hugo" },
      { native: "Manon", roman: "manon" },
      { native: "Arthur", roman: "arthur" },
      { native: "Chloe", roman: "chloe" },
      { native: "Nathan", roman: "nathan" },
      { native: "Ines", roman: "ines" },
      { native: "Jules", roman: "jules" },
      { native: "Emma", roman: "emma" },
      { native: "Raphael", roman: "raphael" },
      { native: "Louise", roman: "louise" },
      { native: "Adam", roman: "adam" },
      { native: "Jade", roman: "jade" },
      { native: "Leo", roman: "leo" },
    ],
    familyNames: [
      { native: "Martin", roman: "martin" },
      { native: "Bernard", roman: "bernard" },
      { native: "Dubois", roman: "dubois" },
      { native: "Moreau", roman: "moreau" },
      { native: "Laurent", roman: "laurent" },
      { native: "Simon", roman: "simon" },
      { native: "Michel", roman: "michel" },
      { native: "Lefevre", roman: "lefevre" },
      { native: "Roux", roman: "roux" },
      { native: "Fournier", roman: "fournier" },
      { native: "Girard", roman: "girard" },
      { native: "Bonnet", roman: "bonnet" },
    ],
  },
  {
    id: "germany",
    countryCode: "DE",
    region: "Germany",
    culture: "engineering quality, understatement, and durable design",
    nameOrder: "given-family",
    defaultLanguages: ["German", "English"],
    givenNames: [
      { native: "Lena", roman: "lena" },
      { native: "Jonas", roman: "jonas" },
      { native: "Mia", roman: "mia" },
      { native: "Leon", roman: "leon" },
      { native: "Emma", roman: "emma" },
      { native: "Finn", roman: "finn" },
      { native: "Sofia", roman: "sofia" },
      { native: "Paul", roman: "paul" },
      { native: "Hannah", roman: "hannah" },
      { native: "Noah", roman: "noah" },
      { native: "Emilia", roman: "emilia" },
      { native: "Luca", roman: "luca" },
      { native: "Lina", roman: "lina" },
      { native: "Elias", roman: "elias" },
      { native: "Marie", roman: "marie" },
      { native: "Felix", roman: "felix" },
    ],
    familyNames: [
      { native: "Mueller", roman: "mueller" },
      { native: "Schmidt", roman: "schmidt" },
      { native: "Schneider", roman: "schneider" },
      { native: "Fischer", roman: "fischer" },
      { native: "Weber", roman: "weber" },
      { native: "Wagner", roman: "wagner" },
      { native: "Becker", roman: "becker" },
      { native: "Hoffmann", roman: "hoffmann" },
      { native: "Schafer", roman: "schafer" },
      { native: "Koch", roman: "koch" },
      { native: "Bauer", roman: "bauer" },
      { native: "Richter", roman: "richter" },
    ],
  },
  {
    id: "italy",
    countryCode: "IT",
    region: "Italy",
    culture: "material beauty, family makers, and living with style",
    nameOrder: "given-family",
    defaultLanguages: ["Italian", "English"],
    givenNames: [
      { native: "Sofia", roman: "sofia" },
      { native: "Lorenzo", roman: "lorenzo" },
      { native: "Giulia", roman: "giulia" },
      { native: "Matteo", roman: "matteo" },
      { native: "Aurora", roman: "aurora" },
      { native: "Alessandro", roman: "alessandro" },
      { native: "Ginevra", roman: "ginevra" },
      { native: "Leonardo", roman: "leonardo" },
      { native: "Alice", roman: "alice" },
      { native: "Francesco", roman: "francesco" },
      { native: "Beatrice", roman: "beatrice" },
      { native: "Edoardo", roman: "edoardo" },
      { native: "Greta", roman: "greta" },
      { native: "Tommaso", roman: "tommaso" },
      { native: "Chiara", roman: "chiara" },
      { native: "Nicolo", roman: "nicolo" },
    ],
    familyNames: [
      { native: "Rossi", roman: "rossi" },
      { native: "Russo", roman: "russo" },
      { native: "Ferrari", roman: "ferrari" },
      { native: "Esposito", roman: "esposito" },
      { native: "Bianchi", roman: "bianchi" },
      { native: "Romano", roman: "romano" },
      { native: "Ricci", roman: "ricci" },
      { native: "Greco", roman: "greco" },
      { native: "Conti", roman: "conti" },
      { native: "Gallo", roman: "gallo" },
      { native: "Costa", roman: "costa" },
      { native: "Fontana", roman: "fontana" },
    ],
  },
  {
    id: "spain",
    countryCode: "ES",
    region: "Spain",
    culture: "social living, design-forward cities, and Mediterranean ease",
    nameOrder: "given-family",
    defaultLanguages: ["Spanish", "English"],
    givenNames: [
      { native: "Lucia", roman: "lucia" },
      { native: "Hugo", roman: "hugo" },
      { native: "Martina", roman: "martina" },
      { native: "Pablo", roman: "pablo" },
      { native: "Sofia", roman: "sofia" },
      { native: "Alejandro", roman: "alejandro" },
      { native: "Daniela", roman: "daniela" },
      { native: "Alvaro", roman: "alvaro" },
      { native: "Carla", roman: "carla" },
      { native: "Mario", roman: "mario" },
      { native: "Paula", roman: "paula" },
      { native: "Diego", roman: "diego" },
      { native: "Alba", roman: "alba" },
      { native: "Manuel", roman: "manuel" },
      { native: "Emma", roman: "emma" },
      { native: "Javier", roman: "javier" },
    ],
    familyNames: [
      { native: "Garcia", roman: "garcia" },
      { native: "Rodriguez", roman: "rodriguez" },
      { native: "Gonzalez", roman: "gonzalez" },
      { native: "Fernandez", roman: "fernandez" },
      { native: "Lopez", roman: "lopez" },
      { native: "Martinez", roman: "martinez" },
      { native: "Sanchez", roman: "sanchez" },
      { native: "Perez", roman: "perez" },
      { native: "Gomez", roman: "gomez" },
      { native: "Ruiz", roman: "ruiz" },
      { native: "Diaz", roman: "diaz" },
      { native: "Moreno", roman: "moreno" },
    ],
  },
  {
    id: "netherlands",
    countryCode: "NL",
    region: "Netherlands",
    culture: "direct taste, cycling cities, and clean functional design",
    nameOrder: "given-family",
    defaultLanguages: ["Dutch", "English"],
    givenNames: [
      { native: "Emma", roman: "emma" },
      { native: "Noah", roman: "noah" },
      { native: "Julia", roman: "julia" },
      { native: "Liam", roman: "liam" },
      { native: "Mila", roman: "mila" },
      { native: "Lucas", roman: "lucas" },
      { native: "Tess", roman: "tess" },
      { native: "Sem", roman: "sem" },
      { native: "Sophie", roman: "sophie" },
      { native: "Daan", roman: "daan" },
      { native: "Saar", roman: "saar" },
      { native: "Luuk", roman: "luuk" },
      { native: "Lotte", roman: "lotte" },
      { native: "Bram", roman: "bram" },
      { native: "Nora", roman: "nora" },
      { native: "Finn", roman: "finn" },
    ],
    familyNames: [
      { native: "de Vries", roman: "devries" },
      { native: "Jansen", roman: "jansen" },
      { native: "de Boer", roman: "deboer" },
      { native: "Visser", roman: "visser" },
      { native: "Smit", roman: "smit" },
      { native: "Meijer", roman: "meijer" },
      { native: "Bakker", roman: "bakker" },
      { native: "Bos", roman: "bos" },
      { native: "Vos", roman: "vos" },
      { native: "Mulder", roman: "mulder" },
      { native: "de Groot", roman: "degroot" },
      { native: "Peters", roman: "peters" },
    ],
  },
  {
    id: "sweden",
    countryCode: "SE",
    region: "Sweden",
    culture: "light, function, and understated everyday beauty",
    nameOrder: "given-family",
    defaultLanguages: ["Swedish", "English"],
    givenNames: [
      { native: "Alice", roman: "alice" },
      { native: "Noah", roman: "noah" },
      { native: "Maja", roman: "maja" },
      { native: "William", roman: "william" },
      { native: "Elsa", roman: "elsa" },
      { native: "Lucas", roman: "lucas" },
      { native: "Astrid", roman: "astrid" },
      { native: "Oscar", roman: "oscar" },
      { native: "Wilma", roman: "wilma" },
      { native: "Liam", roman: "liam" },
      { native: "Vera", roman: "vera" },
      { native: "Elias", roman: "elias" },
      { native: "Alma", roman: "alma" },
      { native: "Hugo", roman: "hugo" },
      { native: "Ebba", roman: "ebba" },
      { native: "Axel", roman: "axel" },
    ],
    familyNames: [
      { native: "Andersson", roman: "andersson" },
      { native: "Johansson", roman: "johansson" },
      { native: "Karlsson", roman: "karlsson" },
      { native: "Nilsson", roman: "nilsson" },
      { native: "Eriksson", roman: "eriksson" },
      { native: "Larsson", roman: "larsson" },
      { native: "Olsson", roman: "olsson" },
      { native: "Persson", roman: "persson" },
      { native: "Svensson", roman: "svensson" },
      { native: "Gustafsson", roman: "gustafsson" },
      { native: "Pettersson", roman: "pettersson" },
      { native: "Jonsson", roman: "jonsson" },
    ],
  },
  {
    id: "australia",
    countryCode: "AU",
    region: "Australia",
    culture: "outdoor ease, beach-to-city products, and independent makers",
    nameOrder: "given-family",
    defaultLanguages: ["English"],
    givenNames: [
      { native: "Isla", roman: "isla" },
      { native: "Jack", roman: "jack" },
      { native: "Mia", roman: "mia" },
      { native: "Oliver", roman: "oliver" },
      { native: "Chloe", roman: "chloe" },
      { native: "Leo", roman: "leo" },
      { native: "Grace", roman: "grace" },
      { native: "Charlie", roman: "charlie" },
      { native: "Ava", roman: "ava" },
      { native: "Harvey", roman: "harvey" },
      { native: "Zoe", roman: "zoe" },
      { native: "Archie", roman: "archie" },
      { native: "Ruby", roman: "ruby" },
      { native: "Max", roman: "max" },
      { native: "Sienna", roman: "sienna" },
      { native: "Henry", roman: "henry" },
    ],
    familyNames: [
      { native: "Nguyen", roman: "nguyen" },
      { native: "Smith", roman: "smith" },
      { native: "Williams", roman: "williams" },
      { native: "Brown", roman: "brown" },
      { native: "Jones", roman: "jones" },
      { native: "Wilson", roman: "wilson" },
      { native: "Taylor", roman: "taylor" },
      { native: "Anderson", roman: "anderson" },
      { native: "Thomas", roman: "thomas" },
      { native: "Jackson", roman: "jackson" },
      { native: "White", roman: "white" },
      { native: "Martin", roman: "martin" },
    ],
  },
  {
    id: "new_zealand",
    countryCode: "NZ",
    region: "New Zealand",
    culture: "nature-first living, honest materials, and small-batch makers",
    nameOrder: "given-family",
    defaultLanguages: ["English"],
    givenNames: [
      { native: "Aroha", roman: "aroha" },
      { native: "Nikau", roman: "nikau" },
      { native: "Amelia", roman: "amelia" },
      { native: "Oliver", roman: "oliver" },
      { native: "Maia", roman: "maia" },
      { native: "Jack", roman: "jack" },
      { native: "Isla", roman: "isla" },
      { native: "Leo", roman: "leo" },
      { native: "Charlotte", roman: "charlotte" },
      { native: "George", roman: "george" },
      { native: "Tane", roman: "tane" },
      { native: "Ruby", roman: "ruby" },
      { native: "Hunter", roman: "hunter" },
      { native: "Sofia", roman: "sofia" },
      { native: "James", roman: "james" },
      { native: "Willow", roman: "willow" },
    ],
    familyNames: [
      { native: "Wilson", roman: "wilson" },
      { native: "Patel", roman: "patel" },
      { native: "Thompson", roman: "thompson" },
      { native: "Williams", roman: "williams" },
      { native: "Ngata", roman: "ngata" },
      { native: "Brown", roman: "brown" },
      { native: "Taylor", roman: "taylor" },
      { native: "Clark", roman: "clark" },
      { native: "Walker", roman: "walker" },
      { native: "Hall", roman: "hall" },
      { native: "Young", roman: "young" },
      { native: "King", roman: "king" },
    ],
  },
  {
    id: "middle_east",
    countryCode: "AE",
    region: "Middle East",
    culture: "hospitality, refined materials, and city-scale modern luxury",
    nameOrder: "given-family",
    defaultLanguages: ["Arabic", "English"],
    countryCodeVariants: ["AE", "SA", "QA", "EG", "JO", "KW"],
    givenNames: [
      { native: "ليلى", roman: "layla" },
      { native: "عمر", roman: "omar" },
      { native: "ياسمين", roman: "yasmin" },
      { native: "آدم", roman: "adam" },
      { native: "نور", roman: "noor" },
      { native: "يوسف", roman: "youssef" },
      { native: "سارة", roman: "sara" },
      { native: "حسن", roman: "hassan" },
      { native: "مريم", roman: "mariam" },
      { native: "خالد", roman: "khalid" },
      { native: "هند", roman: "hind" },
      { native: "زياد", roman: "ziad" },
      { native: "لينا", roman: "lina" },
      { native: "كريم", roman: "karim" },
      { native: "دانة", roman: "dana" },
      { native: "فهد", roman: "fahad" },
    ],
    familyNames: [
      { native: "حسن", roman: "hassan" },
      { native: "ناصر", roman: "nasser" },
      { native: "فارسي", roman: "farsi" },
      { native: "عبدالله", roman: "abdullah" },
      { native: "حسين", roman: "hussein" },
      { native: "صالح", roman: "saleh" },
      { native: "منصور", roman: "mansour" },
      { native: "قاسم", roman: "qasim" },
      { native: "بدر", roman: "badr" },
      { native: "رشيد", roman: "rashid" },
      { native: "عباس", roman: "abbas" },
      { native: "نوفل", roman: "nawfal" },
    ],
  },
  {
    id: "southeast_asia",
    countryCode: "TH",
    region: "Southeast Asia",
    culture: "street-level discovery, hospitality, and rising independent brands",
    nameOrder: "given-family",
    defaultLanguages: ["English", "Chinese"],
    countryCodeVariants: ["TH", "VN", "ID", "MY", "PH"],
    givenNames: [
      { native: "Narin", roman: "narin" },
      { native: "Minh", roman: "minh" },
      { native: "Sari", roman: "sari" },
      { native: "Aisha", roman: "aisha" },
      { native: "Andre", roman: "andre" },
      { native: "Linh", roman: "linh" },
      { native: "Putri", roman: "putri" },
      { native: "Kai", roman: "kai" },
      { native: "Maya", roman: "maya" },
      { native: "Rizky", roman: "rizky" },
      { native: "Anh", roman: "anh" },
      { native: "Sofia", roman: "sofia" },
      { native: "Dewi", roman: "dewi" },
      { native: "Hana", roman: "hana" },
      { native: "Arief", roman: "arief" },
      { native: "Ploy", roman: "ploy" },
    ],
    familyNames: [
      { native: "Sukhum", roman: "sukhum" },
      { native: "Tran", roman: "tran" },
      { native: "Wijaya", roman: "wijaya" },
      { native: "Rahman", roman: "rahman" },
      { native: "Santos", roman: "santos" },
      { native: "Nguyen", roman: "nguyen" },
      { native: "Tanaka", roman: "tanaka" },
      { native: "Lim", roman: "lim" },
      { native: "Cruz", roman: "cruz" },
      { native: "Putra", roman: "putra" },
      { native: "Pham", roman: "pham" },
      { native: "Sari", roman: "sari" },
    ],
  },
];

export const EXPERTISE_CATEGORIES: Record<WorldExpertise, string[]> = {
  technology: ["tech", "lifestyle"],
  economics: ["lifestyle", "fashion", "beauty"],
  business: ["lifestyle", "fashion"],
  fashion: ["fashion", "accessories"],
  beauty: ["beauty", "fragrance"],
  food: ["food", "lifestyle"],
  science: ["tech", "lifestyle"],
  design: ["lifestyle", "fashion", "home"],
  sports: ["sports", "lifestyle"],
  gaming: ["tech", "lifestyle"],
  travel: ["travel", "lifestyle"],
  sustainability: ["lifestyle", "fashion", "home"],
  culture: ["lifestyle", "fashion"],
  media: ["lifestyle", "fashion", "beauty"],
  finance: ["lifestyle", "tech"],
  health: ["lifestyle", "beauty", "food"],
  lifestyle: ["lifestyle", "home"],
};

export const EXPERTISE_PRODUCT_LENS: Record<WorldExpertise, string> = {
  technology: "materials, usability, and whether the object actually improves daily life",
  economics: "price, brand strategy, and marketability",
  business: "positioning, distribution, and whether the brand can last",
  fashion: "silhouette, fabric, and whether it will be worn more than once",
  beauty: "texture, ritual, and whether the formula feels considered",
  food: "origin, craft, and whether it belongs on a real table",
  science: "evidence, materials, and whether the claim is grounded",
  design: "form, proportion, and how it lives in a room or on a body",
  sports: "performance, comfort, and whether it survives real use",
  gaming: "haptics, setup, and whether it makes play better",
  travel: "packability, durability, and whether it earns its weight",
  sustainability: "materials, repairability, and the true cost of making it",
  culture: "local meaning, reference, and whether the object has a place",
  media: "timing, story, and whether people will actually talk about it",
  finance: "value over time, durability, and cost of ownership",
  health: "daily habit, comfort, and whether it supports a real routine",
  lifestyle: "fit in ordinary days, not just a campaign image",
};

export const VALUE_PRODUCT_LENS: Record<WorldValue, string> = {
  innovation: "what is actually new, not just newly advertised",
  quality: "finish, durability, and whether it will age well",
  "price-conscious": "whether the price matches the real usefulness",
  sustainability: "materials, waste, and longevity",
  craftsmanship: "how it was made and who made it",
  convenience: "how little friction it adds to a day",
  "social-impact": "who benefits when this object exists",
  design: "shape, color, and visual intelligence",
  performance: "whether it does the job better than alternatives",
  "brand-story": "whether the story is earned by the object itself",
  "local-culture": "whether it carries a real place, not a costume",
};

export const ROLE_ACTIVITY: Record<WorldRole, "low" | "medium" | "high"> = {
  product_hunter: "high",
  influencer: "high",
  reviewer: "medium",
  fan: "medium",
  critic: "medium",
  media: "medium",
  general_user: "medium",
  trend_hunter: "high",
  curator: "medium",
};
